### ISSUE TITLE
Example #1: Basic Usage -

### ISSUE THREAD

**Issue by jzabroski** [redound/ts-grid#1]
As ts-grid is based on backgrid, it would be nice if ts-grid had parity with backgrid for examples on how to use the data grid, or other HTML5 grid solutions.

Here is a possible outline for creating examples, taken from [Kendo UI Grid](http://demos.telerik.com/kendo-ui/grid/index): 

1. Grid / Basic Usage
   1. How to Instantiate
       1. From an empty div element
       2. From an existing HTML table element.
   2. HTML5/TypeScript source/Widget configuration

**Comment by andevsoftware** [comment]
@jzabroski I don't maintain this repository at the moment. I suggest you fork the existing code base if you would like to use it. It's based of backgrid with multiple adjustments made.
